version: '3'

tasks:
  startApp:
    cmds:
      - clear
      - godotenv -f ./configs/.env go run ./cmd/main.go

  createMigration:
    cmds:
      - migrate create -ext sql -dir ./migrations -seq {{.TITLE}}

  upMigrations:
    cmds: 
      - migrate -database "postgres://{{.LOGIN}}:{{.PASSWORD}}@{{.HOST}}/{{.NAME}}?sslmode=disable" -path ./migrations up

  downMigration:
    cmds: 
      - migrate -database "postgres://{{.LOGIN}}:{{.PASSWORD}}@{{.HOST}}/{{.NAME}}?sslmode=disable" -path ./migrations down 1

  generateSwagger:
    cmds:
      - swag init -g cmd/main.go

  generateProto:
    dir: public
    cmds:
      - |
        protoc \
          --proto_path=./proto \
          --go_out=./pb/golang \
          --go_opt=paths=source_relative \
          --go-grpc_out=./pb/golang \
          --go-grpc_opt=paths=source_relative \
          ./proto/<name>.proto
